### PR TITLE
Fix #342 - Empty PSR4 namespace

### LINKED ISSUE #342: Empty namespace in psr-4/0 will lead to error
## Describe the bug
Using the namespace fallback from `composer.json` where you can use an `""` as namespace produces an error in 
https://github.com/composer-unused/composer-unused/blob/main/src/Command/Handler/CollectConsumedSymbolsCommandHandler.php#L59

We need to validate empty strings as well, maybe even skip them.

## Additional information
https://getcomposer.org/doc/04-schema.md#psr-4
https://getcomposer.org/doc/04-schema.md#psr-0

If you want to have a fallback directory where any namespace will be looked for, you can use an empty prefix like:
```
{
    "autoload": {
        "psr-4": { "": "src/" }
    }
}
```

### PR DESCRIPTION
**Pull request by yoanmLf**
### All Submissions:

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/composer-unused/composer-unused/blob/main/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/icanhazstring/composer-unused/pulls) for the same update/change?

### Changes to Core Features:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
   - See #342 
* [x] Have you written new tests for your core changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Comment by yoanmLf** [comment]
Fill free to propose adjustments if needed

File: tests/Integration/UnusedCommandTest.php [hunk 1]
```diff
@@ -234,6 +234,21 @@ public function itShouldRunWithReadonlyClassInDependency(): void
...
 
+    /**
+     * @test
+     */
+    public function itShouldRunWithEmptyPsr4Namespace(): void
+    {
+        $commandTester = new CommandTester(self::$container->get(UnusedCommand::class));
+        $exitCode = $commandTester->execute(['composer-json' => __DIR__ . '/../assets/TestProjects/EmptyPSR4Namespace/composer.json']);
+
+        self::assertStringContainsString(
```
Comment (icanhazstring) [inline tests/Integration/UnusedCommandTest.php:245]: Can we check for the warning as well?

Comment (yoanmLf) [reply tests/Integration/UnusedCommandTest.php:245]: I wasn't sure, but done 👍 
FYI, I check it with two assertions instead of one because real output is the following
```
 [WARNING] composer.json[autoload][psr-4] contains an empty namespace.                                                  \n
                                                                                                                        \n
           It's usually a bad idea for performance, see output of "composer validate" command.                          \n
```
so quite long, not easy to read, with `\n` at end, and I wonder if spaces count might not be different from a terminal to another one => easier/clearer to check only the two sentences which matters IMO. But feel free to comment if you disagree

**Comment by icanhazstring** [comment]
There is this weird behavior. With columns of console, we might nee to adjust that as you message gets wrapped.

See this thread on Twitter.
https://twitter.com/icanhazstring/status/1576976849129074689?t=YhPik0XzsNLS7wmH23_vwg&s=19

**Comment by icanhazstring** [comment]
Awesome, thanks for the fix :)
