### PR TITLE
Fix Symfony 4 support

### LINKED ISSUE #358: Support for Symfony 4.4 is broken
## Describe the bug
Support for Symfony 4.4 is broken, probably because there's no `--prefer-lowest` CI job to check it. Main stopper for now is this one:
> Fatal error: Uncaught Error: Call to undefined function Symfony\Component\DependencyInjection\Loader\Configurator\service() in /var/www/infacile/vendor/icanhazstring/composer-unused/config/services.php on line 32
>
> Error: Call to undefined function Symfony\Component\DependencyInjection\Loader\Configurator\service() in /var/www/infacile/vendor/icanhazstring/composer-unused/config/services.php on line 32

## Additional information
`service()` function is a rename of the previous `ref()` function in Symfony DI PHP DSL, introduced in 5.1: https://github.com/symfony/symfony/commit/366405b93d670555079605422c5fd05cda23ee08

### PR DESCRIPTION
**Pull request by Jean85**
This should fix #358

[EDIT] It also adds a `--prefer-lowest` job in CI that made the problem appear.

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/composer-unused/composer-unused/blob/main/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/icanhazstring/composer-unused/pulls) for the same update/change?

### CODE REVIEW

File: config/polyfill_symfony_di.php [hunk 1]
```diff
@@ -0,0 +1,12 @@
+<?php
```
Comment (icanhazstring) [inline config/polyfill_symfony_di.php:1]: Clever solution. I like :)

**Review by icanhazstring — APPROVED** [review]
Nice fix. Thanks 👍
